import Head from "next/head";
import Header from "@/components/sections/header";
import Contact from "@/components/sections/contact";
import Education from "@/components/sections/education";
import Skills from "@/components/sections/skills";
import Projects from "@/components/sections/projects";
import Career from "@/components/sections/career";
import Data from "public/data.json";

export default function Home() {
  return (
    <>
      <Head>
        <title>Resume Ben Krocké</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className="page">
        <Header
          name={Data.name}
          title={Data.title}
          contactDetails={Data.contactDetails}
        ></Header>
        {/*<Summary summary={Data.summary} />*/}
        <Career career={Data.career} />
        <Projects projects={Data.projects} />
        <Skills skills={Data.skills} />
        <Education education={Data.education} />
      </main>
    </>
  );
}
